[package]
name = "yadict"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
anyhow = "1"
memmap2 = "0.9"
adler32 = "1.2"
flate2 = "1.1"
nom = "7.1"
regex = "1.12"
ripemd = "0.2"
salsa20 = "0.10"
cipher = "0.5"
encoding = "0.2"
# ratatui = "0.30.0"
clap = { version = "4.6", features = ["derive"] }
minilzo-rs = "0.6"
html2text = "0.17"
ureq = { version = "2.12", features = ["tls"] }
termimad = "0.34"
icu = { version = "1.5", features = ["compiled_data"] }
whatlang = "0.18" # 极其轻量、高效的语言检测库
once_cell = "1.21"

[dev-dependencies]
pretty_env_logger = "0.5"

[dependencies.env_logger]
version = "0.11"
