[package]
name = "yadict"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
anyhow = "1"
memmap2 = "0.9"
adler32 = "1.2.0"
flate2 = "1.1.9"
nom = "7.1.3"
regex = "1.12.3"
ripemd = "0.1.3"
salsa20 = "0.10.2"
cipher = "0.4.4"
encoding = "0.2.33"
ratatui = "0.30.0"
clap = { version = "4", features = ["derive"] }
bytes = "1.11.1"
minilzo-rs = "0.6.0"

[dev-dependencies]
pretty_env_logger = "0.5"

[dependencies.env_logger]
version = "0.11"
